### ISSUE TITLE
Failed to require the module

### ISSUE THREAD

**Issue by hekinami** [ubolonton/emacs-module-rs#1] opened 2018-02-24 08:04 UTC
I followed the user guide and when try to (require 'greeting), the following message showed

ad-Advice-require: Loading file /home/hekinami/.emacs.d/elpa/helm-20180222.2124/helm-command.elc failed to provide feature ‘greeting’

And failed to require.

I tried to (load "greeting"), it returned t, but I cannot use the feature written in the modlue.

**Comment by ubolonton** [comment] 2018-02-24 10:43
The guide missed `libc`. You should have these:

In `Cargo.toml`:
```toml
[dependencies]
libc = "0.2.36"
```
In `src/lib.rs`:
```rust
extern crate libc;
```

Also, if you are on Linux, the symlinking should be
```bash
ln -s libgreeting.so greeting.so
```

I've updated the guide with these.

**Comment by hekinami** [comment] 2018-02-26 03:41
I can make it work with emacs 25.3 now, but still failed with emacs 26.0.91 with the same error messages.

I know 26 has not been released yet, are you already thinking about 26 support now or in your plan?

**Comment by ubolonton** [comment] 2018-02-26 05:02
It should work on 26. CI is set up to test both 25 and 26.

One possible issue may be `module-file-suffix` having a different value. Instead of `(require 'greeting)`, can you try this?

```emacs-lisp
;; Full path, including the extension
(module-load "/full/path/to/greeting.so")
```

Can you provide more details on your Emacs 26 setup? OS version, build configuration...

**Comment by ubolonton** [comment] 2018-04-22 11:40
@hekinami Do you still get the issue?

**Comment by hekinami** [comment] 2018-04-24 08:57
Yes. Please let me try after 26 was released, and will give you feedback then.

**Comment by hekinami** [comment] 2018-05-29 05:49
Hi, @ubolonton  I have just tested in the new released 26.1. Unfortunately, there is still the same issue, when I try to (require 'greeting), we got:

```
Debugger entered--Lisp error: (error "Loading file /home/hekinami/.emacs.d/elpa/ac-racer-20170114.9/ac-racer.elc failed to provide feature ‘greeting’")
  #<subr require>(greeting nil nil)
  ad-Advice-require(#<subr require> greeting)
  apply(ad-Advice-require #<subr require> greeting)
  require(greeting)
  eval((require 'greeting) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x24f263>)(eval-last-sexp nil nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x24f263>) eval-last-sexp)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x24f263>) eval-last-sexp)
  command-execute(eval-last-sexp)
```

and what we got if use 'emacs -Q'

```
Debugger entered--Lisp error: (error "Loading file /usr/local/share/emacs/26.1/lisp/elec-pair.elc failed to provide feature ‘greeting’")
  require(greeting)
  eval((require 'greeting) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

And, by the way, this is the output of 'ls /home/hekinami/sandbox/greeting/target/debug'

> build  deps  examples  greeting.so  incremental  libgreeting.d  libgreeting.so  native

output of 'rustc --version'

> rustc 1.26.0 (a77568041 2018-05-07)

**Comment by tumashu** [comment] 2019-01-16 13:14
Any news? I have faced the same problem when I require emacs module :-(

**Comment by ubolonton** [comment] 2019-03-24 10:48
This seems to be an unresolved bug with Emacs 26 on Linux: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30106.

I'll check later Emacs versions.

**Comment by phst** [comment] 2019-03-24 18:36
Are you sure it's that bug? The bug is marked as "done."

**Comment by ubolonton** [comment] 2019-03-25 03:28
I only skimmed through it. It has the same issue of `load-history` not being correctly modified. I didn't notice it was closed though.

**Comment by ubolonton** [comment] 2019-03-25 04:16
I can reproduce the error with Emacs 26.1 (with both threads and modules), but only on Ubuntu 16.04 (Xenial). On Ubuntu 14.04 (Trusty) and macOS it works fine.

It works on Emacs git snapshot (27.0.50).

Regarding the linked bug, the fix `694ee38f8b7 Fix module support if threads are disabled (Bug#30106)` is not in 26.1.92.

**Comment by tumashu** [comment] 2019-04-14 11:04
Does this problem relate 64OS and 32OS?

**Comment by ubolonton** [comment] 2019-04-14 13:35
> Does this problem relate 64OS and 32OS?

Probably not.

I just tested 26.2. The bug still exists. We'll have to report this upstream.

**Comment by ubolonton** [comment] 2019-04-14 13:37
Even the C module `mod-test` in Emacs's source tree cannot be loaded.

**Comment by ubolonton** [comment] 2019-04-16 08:19
[Emacs commit 694ee38](https://github.com/emacs-mirror/emacs/commit/694ee38) fixed this.

It's in neither 26.1.92 nor 26.2, so you have to wait either for 27, or for the fix to be backported. I added [notes](https://ubolonton.github.io/emacs-module-rs/0.7.0/#known-issues) to the guide.

**Closed by ubolonton** 2019-04-16 08:19 UTC

**Comment by ubolonton** [comment] 2019-04-16 08:21
Thanks @phst btw 🙂
